theme = "mellow"

[editor]
line-number = "relative"
cursorline = true
true-color = true
rulers = [100]
bufferline = "always"
color-modes = true
text-width = 100
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-type", "total-line-numbers", "file-encoding"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"
tab = "all"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "warning"
